export const mockPets = [
  {
    id: "e",
    name: "firulais",
    kg: 420,
    age: 7,
    species: "dog",
    breed: "chihuahua",
    owner: "un señor",
    phone: 2,
    email: "emilio@je",
    temper: "malo",
    gender: "chique",
    img: "foto3",
    symptoms: ["e"],
    exam: {
      temperature: 3,
      hr: 3,
      rr: 3,
      membrane: "e",
      cap: 2,
      sap: 2,
      dap: 2,
      map: 2,
    },
    meds: { fluids: "az", med: "a", ml: 4, hour: 4, via: "a" },
  },
  {
    id: "o",
    name: "chucho",
    kg: 42,
    age: 8,
    species: "dog",
    breed: "chihuahua",
    owner: "una señora",
    phone: 5,
    email: "emilio@je",
    temper: "malo",
    gender: "chique",
    img: "foto4",
    symptoms: ["e"],
    exam: {
      temperature: 3,
      hr: 3,
      rr: 3,
      membrane: "e",
      cap: 2,
      sap: 2,
      dap: 2,
      map: 2,
    },
    meds: { fluids: "a", med: "a", ml: 4, hour: 4, via: "a" },
  },
];
