export const mockPets = [
  {
    id: "e",
    name: "dfsfg",
    kg: 420,
    age: 7,
    species: "dosdfg",
    breed: "chisdfsdfhuahua",
    owner: "un sdsfseñor",
    phone: 2,
    email: "emdsfilio@je",
    temper: "malsdffo",
    gender: "chifdsdque",
    img: "fosdfsto3",
    symptoms: "e",
    temperature: 3,
    hr: 3,
    rr: 3,
    membrane: "e",
    cap: 442,
    sap: 2,
    dap: 233,
    map: 2,
    fluids: "az",
    meds: "a",
    ml: 4,
    hour: 4,
    via: "a",
  },
  {
    id: "o",
    name: "chsdfucho",
    kg: 42,
    age: 8,
    species: "ddsfog",
    breed: "chifdsfhuahua",
    owner: "unaseñora",
    phone: 5,
    email: "emilisdfo@je",
    temper: "maldzsfo",
    gender: "chifsdque",
    img: "fofsfto4",
    symptoms: "e",
    temperature: 3,
    hr: 3,
    rr: 3,
    membrane: "e",
    cap: 2,
    sap: 2,
    dap: 2,
    map: 2,
    fluids: "sdfa",
    meds: "dfsa",
    ml: 4,
    hour: 4,
    via: "sfa",
  },
];

export const mockPet = {
  id: "e",
  name: "firulais",
  kg: 420,
  age: 7,
  species: "dog",
  breed: "chihuahua",
  owner: "un señor",
  phone: 2,
  email: "emilio@je",
  temper: "malo",
  gender: "chique",
  img: "foto8",
  symptoms: "e",
  temperature: 3,
  hr: 3,
  rr: 3,
  membrane: "e",
  cap: 2,
  sap: 2,
  dap: 2,
  map: 2,
  fluids: "a",
  meds: "a",
  ml: 4,
  hour: 4,
  via: "a",
};

export const mockPetEmpty = {
  id: "",
  name: "pepe",
  kg: 40,
  age: 77,
  species: "puppy",
  breed: "lab",
  owner: "un tipo",
  phone: 233,
  email: "pepa@je",
  temper: "bueno",
  gender: "chico",
  img: "foto83",
  symptoms: "eeee",
  temperature: 32,
  hr: 23,
  rr: 32,
  membrane: "eeeej",
  cap: 21,
  sap: 21,
  dap: 22,
  map: 26,
  fluids: "atr",
  meds: "arty",
  ml: 4,
  hour: 49,
  via: "rya",
};
