export const mockPets = [
  {
    id: "e",
    name: "dfsfg",
    kg: 420,
    age: 7,
    species: "dosdfg",
    breed: "chisdfsdfhuahua",
    owner: "un sdsfseñor",
    phone: 2,
    email: "emdsfilio@je",
    temper: "malsdffo",
    gender: "chifdsdque",
    img: "fosdfsto3",
    symptoms: ["e"],
    exam: {
      temperature: 3,
      hr: 3,
      rr: 3,
      membrane: "e",
      cap: 442,
      sap: 2,
      dap: 233,
      map: 2,
    },
    meds: { fluids: "az", med: "a", ml: 4, hour: 4, via: "a" },
  },
  {
    id: "o",
    name: "chsdfucho",
    kg: 42,
    age: 8,
    species: "ddsfog",
    breed: "chifdsfhuahua",
    owner: "unaseñora",
    phone: 5,
    email: "emilisdfo@je",
    temper: "maldzsfo",
    gender: "chifsdque",
    img: "fofsfto4",
    symptoms: ["e"],
    exam: {
      temperature: 3,
      hr: 3,
      rr: 3,
      membrane: "e",
      cap: 2,
      sap: 2,
      dap: 2,
      map: 2,
    },
    meds: { fluids: "sdfa", med: "dfsa", ml: 4, hour: 4, via: "sfa" },
  },
];

export const mockPet = {
  id: "e",
  name: "firulais",
  kg: 420,
  age: 7,
  species: "dog",
  breed: "chihuahua",
  owner: "un señor",
  phone: 2,
  email: "emilio@je",
  temper: "malo",
  gender: "chique",
  img: "foto8",
  symptoms: ["e"],
  exam: {
    temperature: 3,
    hr: 3,
    rr: 3,
    membrane: "e",
    cap: 2,
    sap: 2,
    dap: 2,
    map: 2,
  },
  meds: { fluids: "a", med: "a", ml: 4, hour: 4, via: "a" },
};
